import { builtinModules as builtins } from 'module';

/**
 * Shared esbuild options for all Merlay bundles.
 * Per-host configs (packages/obsidian, packages/vscode) import these
 * and add their own entryPoints / format / externals / outfile.
 */

export const sharedOptions = {
  bundle: true,
  target: 'es2022',
  logLevel: 'info',
  treeShaking: true,
  jsx: 'automatic',
};

/** Modules provided by the Obsidian runtime — never bundled. */
export const obsidianExternals = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtins,
];

export const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
